import * as THREE from 'three';
import { Enemy, EnemyConfig } from './Enemy';

export const ENEMY_ARCHETYPES: Record<string, EnemyConfig> = {
  swordsman: {
    name: 'Sparring Ashigaru',
    archetype: 'swordsman',
    maxHealth: 85,
    maxPosture: 80,
    walkSpeed: 3.2,
    runSpeed: 6.2,
    attackRange: 2.3,
    attackCooldown: 1.4,
    parryChance: 0.25,
    canThrust: true,
    canSweep: false,
    trailColor: 0xffffff,
  },
  duelist: {
    name: 'Crimson Duelist',
    archetype: 'duelist',
    maxHealth: 100,
    maxPosture: 95,
    walkSpeed: 4.2,
    runSpeed: 7.8,
    attackRange: 2.2,
    attackCooldown: 0.9,
    parryChance: 0.55,
    canThrust: true,
    canSweep: true,
    trailColor: 0xff4d4f,
  },
  heavy: {
    name: 'Iron Mountain Brute',
    archetype: 'heavy',
    maxHealth: 160,
    maxPosture: 150,
    walkSpeed: 2.4,
    runSpeed: 4.8,
    attackRange: 2.8,
    attackCooldown: 1.8,
    parryChance: 0.1,
    canThrust: false,
    canSweep: true,
    trailColor: 0xff922b,
  },
  spear: {
    name: 'Sohei Spear Master',
    archetype: 'spear',
    maxHealth: 90,
    maxPosture: 90,
    walkSpeed: 3.5,
    runSpeed: 6.8,
    attackRange: 3.4,
    attackCooldown: 1.2,
    parryChance: 0.35,
    canThrust: true,
    canSweep: true,
    trailColor: 0x69db7c,
  },
  assassin: {
    name: 'Shadow Shinobi',
    archetype: 'assassin',
    maxHealth: 75,
    maxPosture: 70,
    walkSpeed: 4.8,
    runSpeed: 9.0,
    attackRange: 2.0,
    attackCooldown: 0.8,
    parryChance: 0.45,
    canThrust: true,
    canSweep: false,
    trailColor: 0x9775fa,
  },
  knight: {
    name: 'Elite Kurogane Knight',
    archetype: 'knight',
    maxHealth: 125,
    maxPosture: 130,
    walkSpeed: 3.6,
    runSpeed: 7.0,
    attackRange: 2.6,
    attackCooldown: 1.0,
    parryChance: 0.7,
    canThrust: true,
    canSweep: true,
    trailColor: 0xffd43b,
  },
  monk: {
    name: 'Yamabushi Ascetic',
    archetype: 'monk',
    maxHealth: 110,
    maxPosture: 110,
    walkSpeed: 4.0,
    runSpeed: 7.5,
    attackRange: 2.2,
    attackCooldown: 1.1,
    parryChance: 0.4,
    canThrust: true,
    canSweep: true,
    trailColor: 0x20c997,
  },
};

export function spawnEnemyArchetype(
  scene: THREE.Scene,
  type: string,
  spawnPos: THREE.Vector3
): Enemy {
  const config = ENEMY_ARCHETYPES[type] || ENEMY_ARCHETYPES.swordsman;
  return new Enemy(scene, config, spawnPos);
}
