import * as THREE from 'three';
import { Enemy, EnemyConfig } from './Enemy';

export const ENEMY_ARCHETYPES: Record<string, EnemyConfig> = {
  swordsman: {
    name: 'Sparring Ashigaru',
    archetype: 'swordsman',
    maxHealth: 100,
    maxPosture: 100,
    walkSpeed: 3.8,
    runSpeed: 7.0,
    attackRange: 2.5,
    attackCooldown: 0.8,
    parryChance: 0.85, // Actively clashes and deflects player attacks!
    canThrust: true,
    canSweep: false,
    trailColor: 0xffffff,
  },
  duelist: {
    name: 'Crimson Duelist',
    archetype: 'duelist',
    maxHealth: 120,
    maxPosture: 120,
    walkSpeed: 4.5,
    runSpeed: 8.5,
    attackRange: 2.4,
    attackCooldown: 0.55, // Relentless aggression
    parryChance: 0.92,
    canThrust: true,
    canSweep: true,
    trailColor: 0xff4d4f,
  },
  heavy: {
    name: 'Iron Mountain Brute',
    archetype: 'heavy',
    maxHealth: 200,
    maxPosture: 180,
    walkSpeed: 3.0,
    runSpeed: 5.6,
    attackRange: 3.0,
    attackCooldown: 1.1,
    parryChance: 0.45,
    canThrust: false,
    canSweep: true,
    trailColor: 0xff922b,
  },
  spear: {
    name: 'Sohei Spear Master',
    archetype: 'spear',
    maxHealth: 110,
    maxPosture: 110,
    walkSpeed: 4.0,
    runSpeed: 7.5,
    attackRange: 3.6,
    attackCooldown: 0.7,
    parryChance: 0.88,
    canThrust: true,
    canSweep: true,
    trailColor: 0x69db7c,
  },
  assassin: {
    name: 'Shadow Shinobi',
    archetype: 'assassin',
    maxHealth: 90,
    maxPosture: 90,
    walkSpeed: 5.2,
    runSpeed: 9.8,
    attackRange: 2.2,
    attackCooldown: 0.5,
    parryChance: 0.88,
    canThrust: true,
    canSweep: false,
    trailColor: 0x9775fa,
  },
  knight: {
    name: 'Elite Kurogane Knight',
    archetype: 'knight',
    maxHealth: 150,
    maxPosture: 160,
    walkSpeed: 4.0,
    runSpeed: 7.6,
    attackRange: 2.8,
    attackCooldown: 0.65,
    parryChance: 0.95,
    canThrust: true,
    canSweep: true,
    trailColor: 0xffd43b,
  },
  monk: {
    name: 'Yamabushi Ascetic',
    archetype: 'monk',
    maxHealth: 130,
    maxPosture: 130,
    walkSpeed: 4.4,
    runSpeed: 8.0,
    attackRange: 2.4,
    attackCooldown: 0.7,
    parryChance: 0.85,
    canThrust: true,
    canSweep: true,
    trailColor: 0x20c997,
  },
};

export function spawnEnemyArchetype(
  scene: THREE.Scene,
  type: string,
  spawnPos: THREE.Vector3
): Enemy {
  const config = ENEMY_ARCHETYPES[type] || ENEMY_ARCHETYPES.swordsman;
  return new Enemy(scene, config, spawnPos);
}
